### ISSUE TITLE
CORS problem on clear startup in gitpod

### ISSUE THREAD

**Issue by Amantel** [marcopeg/fetchq-cron#84]
How to reproduce: 
1. Launch repo in gitpod
2. Wait for everything to finish loading

![image](https://user-images.githubusercontent.com/575862/77907408-42385080-7292-11ea-851a-62718a97e316.png)

**Comment by Amantel** [comment]
I will try to use env setting from https://github.com/marcopeg/fetchq-cron/issues/76

**Comment by Amantel** [comment]
Nope, setting development ENV does not help 
![image](https://user-images.githubusercontent.com/575862/77908268-da830500-7293-11ea-9189-9df60b86de38.png)

**Comment by Amantel** [comment]
Here is the description of the error: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

**Comment by Amantel** [comment]
Setting withCredentials & credentials in config to false, as suggested in mozilla article - helped. I am not sure if I should do a pull request here. 
![image](https://user-images.githubusercontent.com/575862/77909591-4d8d7b00-7296-11ea-94e9-44c205d9c9a8.png)

**Comment by Amantel** [comment]
Only first two settings matter and they can be set using process.env.NODE_ENV !== 'development'

**Comment by marcopeg** [comment]
Eventually, we found out that a Firefox plugin was responsible for the weird behavior:
https://addons.mozilla.org/en-US/firefox/addon/access-control-allow-origin/

big thanks to @Amantel for contributing to this finding :-)
